ccflags-y += -I$(srctree)/drivers/misc/moto-dtv

obj-$(CONFIG_MOTO_DTV_FC8300) += isdbt.o
isdbt-objs := bbm.o fc8300.o fc8300_bb.o fc8300_i2c.o fc8300_isr.o fc8300_ppi.o fc8300_spi.o fc8300_tun.o fc8300_tun_table.o fci_hal.o fci_hpi.o fci_oal.o fci_ringbuffer.o fci_tun.o
